"""Generated Sprint loop diagram for the root README.

The controller owns the flow, so the diagram is rendered from controller
constants (``forge.orchestrator`` iteration phases and ``forge.sprint``
schedule constants) instead of being a one-off picture. Refresh the README
with::

    python3 -m forge.diagram --update README.md

and keep it in sync mechanically::

    python3 -m forge.diagram --check README.md
"""

from __future__ import annotations

import argparse
import sys

from .sprint import CODER_CANDIDATES, MIN_BACKLOG_STORIES, SPRINT_SCHEDULE
from .orchestrator import ITERATION_PHASES

DIAGRAM_BEGIN = "<!-- forge:sprint-loop-diagram:begin -->"
DIAGRAM_END = "<!-- forge:sprint-loop-diagram:end -->"

_PHASE_LABELS = {
    "planning": "planner<br>immutable task plan",
    "test-authoring": "test author<br>RED pytest suite",
    "coding": "coder tournament<br>tdd / explore / classic<br>isolated worktrees",
    "selection": "reviewer selects the winner",
    "review": "review",
    "fixing": "winner-fix round",
    "testing": "unified tester<br>white-box + black-box",
    "delivery": "exact-tree commit<br>and delivery",
    "finalizing": "finalization<br>worktrees cleaned up",
}


def render_diagram() -> str:
    """Render the Sprint loop flowchart from the controller constants."""

    if sorted(_PHASE_LABELS) != sorted(ITERATION_PHASES):
        raise ValueError("phase labels in forge.diagram do not match the controller phases")
    schedule = " / ".join(kind[0].upper() for kind in SPRINT_SCHEDULE)
    coders = " / ".join(CODER_CANDIDATES)
    slots = f"{len(SPRINT_SCHEDULE)} slots ({schedule})"
    return f"""{DIAGRAM_BEGIN}
```mermaid
%% Generated by forge.diagram from the controller constants; do not edit by hand.
%% Refresh: python3 -m forge.diagram --update README.md
flowchart TB
    snapshot(["committed product snapshot"]) --> po["fresh Product Owner<br>opens a deep backlog<br>at least {MIN_BACKLOG_STORIES} stories / one hour of work"]
    po --> slot{{"{slots}<br>F = feature, C = cleanup only"}}
    slot --> iteration
    subgraph iteration["one accepted iteration"]
        direction TB
        planning["{_PHASE_LABELS['planning']}"]
        planning --> test_authoring["{_PHASE_LABELS['test-authoring']}"]
        test_authoring --> coding["{_PHASE_LABELS['coding']}"]
        coding --> selection["{_PHASE_LABELS['selection']}"]
        selection --> review{{"review"}}
        review -- "reject" --> fixing["{_PHASE_LABELS['fixing']}"]
        fixing --> review
        review -- "accepted" --> testing["{_PHASE_LABELS['testing']}"]
        testing -- "reject" --> review
        testing -- "accepted" --> delivery["{_PHASE_LABELS['delivery']}"]
        delivery --> finalizing["{_PHASE_LABELS['finalizing']}"]
    end
    finalizing --> slot
    classDef gate fill:#faf5ff,stroke:#8250df,stroke-width:2px,color:#24292f;
    classDef role fill:#f0f6ff,stroke:#0969da,color:#24292f;
    classDef loop fill:#ffffff,stroke:#0969da,stroke-width:2px,color:#24292f;
    class review,testing gate;
    class po,planning,test_authoring,coding,selection,fixing,delivery,finalizing role;
    class iteration loop;
```
{DIAGRAM_END}"""


def _read_marked_section(path: str) -> tuple[int, int, list[str]]:
    with open(path, encoding="utf-8") as handle:
        lines = handle.read().splitlines()
    try:
        start = lines.index(DIAGRAM_BEGIN)
        end = lines.index(DIAGRAM_END)
    except ValueError:
        raise SystemExit(f"{path}: {DIAGRAM_BEGIN}..{DIAGRAM_END} markers not found")
    return start, end, lines


def update_readme(path: str) -> None:
    start, end, lines = _read_marked_section(path)
    lines[start : end + 1] = render_diagram().splitlines()
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def check_readme(path: str) -> bool:
    start, end, lines = _read_marked_section(path)
    return lines[start : end + 1] == render_diagram().splitlines()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python3 -m forge.diagram",
        description="Render the README Sprint loop diagram from the controller.",
    )
    parser.add_argument("readme", nargs="?", help="path to the README to check or update")
    parser.add_argument("--update", action="store_true", help="rewrite the marked section")
    parser.add_argument("--check", action="store_true", help="exit 1 when the section is stale")
    args = parser.parse_args(argv)
    if args.update or args.check:
        if not args.readme:
            parser.error("a README path is required with --update or --check")
        if args.update:
            update_readme(args.readme)
            print(f"updated {args.readme}")
        return 0 if check_readme(args.readme) else 1
    print(render_diagram())
    return 0


if __name__ == "__main__":
    sys.exit(main())
